declare const LUAM_VERSION: string | undefined;

export const VERSION = typeof LUAM_VERSION === 'string' ? LUAM_VERSION : '0.0.0-dev';

export const USAGE = [
    'luam — the Luam compiler for Multi Theft Auto resources.',
    '',
    'Usage:',
    '    luam <command> [options]',
    '    luam init [path] [options]',
    '',
    'Commands:',
    '    build     Compile the project and write the resource to the output directory.',
    '    check     Compile the project and report diagnostics without writing files.',
    '    dev       Build, sync, restart, watch, and stream resource development logs.',
    '    doctor    Check the CLI, supported editors, and the Luam extension.',
    '    ensure    Build, sync the resource into the MTA server, and restart it.',
    '    init      Interactively scaffold a new resource project.',
    '    setup     Detect supported editors and install the Luam extension with consent.',
    '    trace     Resolve generated Lua positions back to Luam source positions.',
    '',
    'Options:',
    '    --cwd <path>       Project directory that contains luam.json. Defaults to the current directory.',
    '    --config <path>    Configuration file to load instead of luam.json.',
    '    --name <name>      Resource name for init. Defaults to the destination directory name.',
    '    --force            Let init overwrite files that already exist.',
    '    -y, --yes          Accept init defaults or install every detected editor without prompting.',
    '    --watch            Keep ensure or dev running and rebuild on source changes.',
    '    --no-watch         Run ensure or dev once and exit.',
    '    --bundle           Build or ensure with bundled output.',
    '    --no-bundle        Build or ensure with tree output.',
    '    --no-map           Disable resource map generation.',
    '    --map <path>       Resource map to use for trace.',
    '    --offline          Skip the MTA release lookup and use the cached version, if there is one.',
    '    --no-color         Print plain output with no colour and no emoji.',
    '    -h, --help         Show this help text.',
    '    -v, --version      Show the CLI version.',
    '',
    'Exit codes:',
    '    0    The command succeeded.',
    '    1    The command reported diagnostics or could not complete setup.',
    '    2    The command line or configuration is invalid.',
].join('\n');
