export const VERSION = '0.0.0';

export const USAGE = [
    'luam — the Luam compiler for Multi Theft Auto resources.',
    '',
    'Usage:',
    '    luam <command> [options]',
    '',
    'Commands:',
    '    build     Compile the project and write the resource to the output directory.',
    '    check     Compile the project and report diagnostics without writing files.',
    '    ensure    Build, sync the resource into the MTA server, and restart it.',
    '    init      Scaffold a new resource project with the framework and example handlers.',
    '',
    'Options:',
    '    --cwd <path>       Project directory that contains luam.json. Defaults to the current directory.',
    '    --config <path>    Configuration file to load instead of luam.json.',
    '    --name <name>      Resource name for init. Defaults to the project directory name.',
    '    --force            Let init overwrite files that already exist.',
    '    --watch            Keep ensure running and rebuild on source changes.',
    '    --no-watch         Run ensure once and exit.',
    '    --offline          Skip the MTA release lookup and use the cached version, if there is one.',
    '    --no-color         Print plain output with no colour and no emoji.',
    '    -h, --help         Show this help text.',
    '    -v, --version      Show the CLI version.',
    '',
    'Exit codes:',
    '    0    The command succeeded.',
    '    1    The build reported diagnostics.',
    '    2    The command line or configuration is invalid.',
].join('\n');
