import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';

import { EXIT_DIAGNOSTICS, EXIT_OK } from '@cli/cli/exit-codes';
import type { Reporter } from '@cli/reporting/reporter';
import { extractConfigDeclarations, isGeneratedDeclaration, renderConfigDeclarations } from '@compiler/project/config-extractor';

export const DEFAULT_CONFIG_SOURCE = 'config.lua';

export const DEFAULT_CONFIG_OUTPUT = 'config.d.luam';

export interface ConfigCommandOptions {
    source?: string | null;
    out?: string | null;
    write?: boolean;
}

function escapes(root: string, path: string): boolean {
    const inside = relative(root, path);

    return inside.startsWith('..') || resolve(root, inside) !== path;
}

function readSource(root: string, source: string, reporter: Reporter): string | null {
    const path = resolve(root, source);

    if (escapes(root, path)) {
        reporter.error(`Config declarations read only inside the project, but "${source}" points outside it.`);

        return null;
    }

    if (!existsSync(path)) {
        reporter.error(`Config declarations found no file at "${source}".`);

        return null;
    }

    try {
        return readFileSync(path, 'utf8');
    } catch {
        reporter.error(`Config declarations could not read "${source}".`);

        return null;
    }
}

function writable(root: string, out: string, reporter: Reporter): string | null {
    const path = resolve(root, out);

    if (escapes(root, path)) {
        reporter.error(`Config declarations write only inside the project, but "${out}" points outside it.`);

        return null;
    }

    if (existsSync(path) && !isGeneratedDeclaration(readFileSync(path, 'utf8'))) {
        reporter.error(`"${out}" was not generated by this command and was left alone. Choose another path with --out.`);

        return null;
    }

    return path;
}

export function runConfigCommand(root: string, reporter: Reporter, options: ConfigCommandOptions = {}): number {
    const source = options.source ?? DEFAULT_CONFIG_SOURCE;
    const out = options.out ?? DEFAULT_CONFIG_OUTPUT;
    const text = readSource(root, source, reporter);

    if (text === null) {
        return EXIT_DIAGNOSTICS;
    }

    const extracted = extractConfigDeclarations(text);

    for (const problem of extracted.problems) {
        reporter.warn(`${source}:${problem.line}:${problem.column} ${problem.message}`);
    }

    if (extracted.declarations.length === 0) {
        reporter.error(`Config declarations found nothing to declare in "${source}".`);

        return EXIT_DIAGNOSTICS;
    }

    const rendered = renderConfigDeclarations(source, extracted.declarations);

    if (options.write !== true) {
        reporter.info(rendered.trimEnd());
        reporter.info(`Config declarations would write ${extracted.declarations.length} name(s) to "${out}". Pass --write to save it.`);

        return EXIT_OK;
    }

    const path = writable(root, out, reporter);

    if (path === null) {
        return EXIT_DIAGNOSTICS;
    }

    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, rendered, 'utf8');
    reporter.info(`Config declarations wrote ${extracted.declarations.length} name(s) to "${out}".`);

    return EXIT_OK;
}
