import { contrast } from '@theme/color';
import { MODES, SURFACES } from '@theme/palette';
import { resolve } from '@theme/resolve';
import { ROLES } from '@theme/roles';

export type DocsLocale = 'en' | 'pt-br';

export const DOCS_LOCALES: readonly DocsLocale[] = ['en', 'pt-br'];

const HEADERS: Readonly<Record<DocsLocale, readonly string[]>> = {
    en: ['Element', 'Group', 'Dark', 'Light', 'Style', 'Layer'],
    'pt-br': ['Elemento', 'Grupo', 'Escuro', 'Claro', 'Estilo', 'Camada'],
};

const NOTICE: Readonly<Record<DocsLocale, string>> = {
    en: 'Generated by @luam/theme from the role table. Do not edit by hand.',
    'pt-br': 'Gerado por @luam/theme a partir da tabela de papéis. Não edite à mão.',
};

const STYLE_TEXT: Readonly<Record<string, string>> = {
    none: '—',
    bold: 'bold',
    italic: 'italic',
};

function row(cells: readonly string[]): string {
    return `| ${cells.join(' | ')} |`;
}

export function elementTable(locale: DocsLocale): string {
    const header = HEADERS[locale];
    const rows = ROLES.map((role) =>
        row([
            `\`${role.id}\``,
            `\`${role.set}\``,
            `\`${resolve(role, 'dark').foreground}\``,
            `\`${resolve(role, 'light').foreground}\``,
            STYLE_TEXT[role.style] ?? role.style,
            role.layer,
        ]),
    );

    return [`<!-- ${NOTICE[locale]} -->`, '', row([...header]), row(header.map(() => '---')), ...rows, ''].join('\n');
}

export function contrastTable(locale: DocsLocale): string {
    const header = locale === 'en' ? ['Mode', 'Lowest role', 'Ratio', 'Floor'] : ['Modo', 'Menor papel', 'Razão', 'Piso'];
    const rows = MODES.map((mode) => {
        const background = SURFACES[mode].background;
        const measured = ROLES.map((role) => ({ role, ratio: contrast(resolve(role, mode).foreground, background) })).sort(
            (first, second) => first.ratio - second.ratio,
        );
        const lowest = measured[0];

        return row([mode, `\`${lowest?.role.id ?? ''}\``, `${lowest?.ratio ?? 0}:1`, `${lowest?.role.ambient === true ? '3' : '4.5'}:1`]);
    });

    return [`<!-- ${NOTICE[locale]} -->`, '', row([...header]), row(header.map(() => '---')), ...rows, ''].join('\n');
}

export function sampleBlock(fixture: string): string {
    return [`<!-- ${NOTICE.en} -->`, '', '```luam static', fixture.replace(/\r\n/g, '\n').trimEnd(), '```', ''].join('\n');
}
