import { chrome, resolve } from '@theme/resolve';
import { MODES, type Mode } from '@theme/palette';
import { roleForToken, SEMANTIC_SELECTORS, TOKEN_TYPES } from '@theme/targets/semantic';

const HEADER: readonly string[] = [
    '-- Luam colour scheme. Generated by @luam/theme; do not edit by hand.',
    '-- Luam has no Tree-sitter grammar, so every syntax colour below comes from',
    '-- the Luam language server. Configure it before expecting colour.',
];

const SYNTAX_GROUPS: Readonly<Record<string, string>> = {
    Boolean: 'literal.string',
    Character: 'literal.constant',
    Comment: 'comment',
    Constant: 'identifier.member',
    Delimiter: 'punctuation',
    Function: 'call.function',
    Identifier: 'identifier.local',
    Keyword: 'keyword',
    Number: 'literal.string',
    Operator: 'punctuation',
    PreProc: 'directive.strictness',
    Special: 'punctuation.interpolation',
    Statement: 'keyword',
    String: 'literal.string',
    Structure: 'name.type',
    Type: 'type.name',
};

function quote(value: string): string {
    return `'${value}'`;
}

function highlight(group: string, options: readonly string[]): string {
    return `        hl(0, '${group}', { ${options.join(', ')} })`;
}

function styleOptions(role: string, mode: Mode): string[] {
    const resolved = resolve(role, mode);
    const options = [`fg = ${quote(resolved.foreground)}`];

    if (resolved.fontStyle === 'bold') {
        options.push('bold = true');
    }

    if (resolved.fontStyle === 'italic') {
        options.push('italic = true');
    }

    return options;
}

function chromeLines(mode: Mode): string[] {
    const surface = chrome(mode);

    return [
        highlight('Normal', [`fg = ${quote(surface.foreground)}`, `bg = ${quote(surface.background)}`]),
        highlight('NormalFloat', [`fg = ${quote(surface.foreground)}`, `bg = ${quote(surface.elevated)}`]),
        highlight('FloatBorder', [`fg = ${quote(surface.line)}`, `bg = ${quote(surface.elevated)}`]),
        highlight('LineNr', [`fg = ${quote(surface.gutter)}`]),
        highlight('CursorLineNr', [`fg = ${quote(surface.gutterActive)}`]),
        highlight('CursorLine', [`bg = ${quote(surface.surface)}`]),
        highlight('Visual', [`bg = ${quote(surface.elevated)}`]),
        highlight('MatchParen', [`bg = ${quote(surface.elevated)}`, 'bold = true']),
        highlight('Pmenu', [`fg = ${quote(surface.foreground)}`, `bg = ${quote(surface.elevated)}`]),
        highlight('PmenuSel', [`fg = ${quote(surface.background)}`, `bg = ${quote(surface.accent)}`]),
        highlight('StatusLine', [`fg = ${quote(surface.foreground)}`, `bg = ${quote(surface.surface)}`]),
        highlight('TabLine', [`fg = ${quote(surface.dimForeground)}`, `bg = ${quote(surface.surface)}`]),
        highlight('TabLineSel', [`fg = ${quote(surface.foreground)}`, `bg = ${quote(surface.background)}`]),
        highlight('VertSplit', [`fg = ${quote(surface.line)}`]),
        highlight('LspInlayHint', [`fg = ${quote(surface.inlayHint)}`, `bg = ${quote(surface.elevated)}`]),
        highlight('DiagnosticError', [`fg = ${quote(surface.error)}`]),
        highlight('DiagnosticWarn', [`fg = ${quote(surface.warning)}`]),
        highlight('DiagnosticInfo', [`fg = ${quote(surface.info)}`]),
        highlight('DiagnosticHint', [`fg = ${quote(surface.hint)}`]),
        highlight('DiffAdd', [`fg = ${quote(surface.added)}`]),
        highlight('DiffChange', [`fg = ${quote(surface.modified)}`]),
        highlight('DiffDelete', [`fg = ${quote(surface.removed)}`]),
    ];
}

function semanticGroups(): Map<string, string> {
    const groups = new Map<string, string>();

    for (const type of TOKEN_TYPES) {
        const role = roleForToken(type, []);

        if (role !== null) {
            groups.set(`@lsp.type.${type}`, role);
        }
    }

    for (const entry of SEMANTIC_SELECTORS) {
        const segments = entry.selector.split('.');
        const type = segments[0] as string;
        const modifier = segments[segments.length - 1] as string;

        if (segments.length < 2) {
            continue;
        }

        groups.set(type === '*' ? `@lsp.mod.${modifier}` : `@lsp.typemod.${type}.${modifier}`, entry.role);
    }

    return groups;
}

function modeBlock(mode: Mode): string[] {
    const groups = Object.keys(SYNTAX_GROUPS)
        .sort()
        .map((group) => highlight(group, styleOptions(SYNTAX_GROUPS[group] as string, mode)));
    const semantic = [...semanticGroups()].map(([group, role]) => highlight(group, styleOptions(role, mode)));

    return [`    if mode == '${mode}' then`, ...chromeLines(mode), '', ...groups, '', ...semantic, '    end', ''];
}

export function buildNeovimTheme(): string {
    return [
        ...HEADER,
        '',
        'local M = {}',
        '',
        'local function apply(hl, mode)',
        ...MODES.flatMap(modeBlock),
        'end',
        '',
        'function M.setup()',
        "    vim.g.colors_name = 'luam'",
        '',
        "    apply(vim.api.nvim_set_hl, vim.o.background == 'light' and 'light' or 'dark')",
        'end',
        '',
        'return M',
        '',
    ].join('\n');
}
