import { chrome, resolve } from '@theme/resolve';
import type { Mode } from '@theme/palette';
import { ROLES } from '@theme/roles';
import { scopesFor } from '@theme/targets/textmate';
import { THEME_LABELS } from '@theme/targets/vscode';

function escape(value: string): string {
    return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function entry(key: string, value: string): string[] {
    return [`\t\t\t\t<key>${escape(key)}</key>`, `\t\t\t\t<string>${escape(value)}</string>`];
}

function globalSettings(mode: Mode): string[] {
    const surface = chrome(mode);

    return [
        '\t\t<dict>',
        '\t\t\t<key>settings</key>',
        '\t\t\t<dict>',
        ...entry('background', surface.background),
        ...entry('foreground', surface.foreground),
        ...entry('caret', surface.cursor),
        ...entry('lineHighlight', surface.lineHighlight),
        ...entry('selection', surface.selection),
        ...entry('invisibles', surface.line),
        ...entry('gutterForeground', surface.gutter),
        '\t\t\t</dict>',
        '\t\t</dict>',
    ];
}

function roleSettings(role: string, scopes: readonly string[], mode: Mode): string[] {
    const resolved = resolve(role, mode);
    const style = resolved.fontStyle === 'none' ? [] : entry('fontStyle', resolved.fontStyle);

    return [
        '\t\t<dict>',
        '\t\t\t<key>name</key>',
        `\t\t\t<string>${escape(role)}</string>`,
        '\t\t\t<key>scope</key>',
        `\t\t\t<string>${escape(scopes.join(', '))}</string>`,
        '\t\t\t<key>settings</key>',
        '\t\t\t<dict>',
        ...entry('foreground', resolved.foreground),
        ...style,
        '\t\t\t</dict>',
        '\t\t</dict>',
    ];
}

export function buildTmTheme(mode: Mode): string {
    const rules = ROLES.flatMap((role) => {
        const scopes = scopesFor(role.id);

        return scopes.length === 0 ? [] : roleSettings(role.id, scopes, mode);
    });

    return [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
        '<!-- Generated by @luam/theme from the role table. Do not edit by hand. -->',
        '<plist version="1.0">',
        '<dict>',
        '\t<key>name</key>',
        `\t<string>${escape(THEME_LABELS[mode])}</string>`,
        '\t<key>settings</key>',
        '\t<array>',
        ...globalSettings(mode),
        ...rules,
        '\t</array>',
        '\t<key>uuid</key>',
        `\t<string>${mode === 'dark' ? '9a7e6c1d-2f4b-4a58-9c31-1d5b7f0a2e64' : '3c8f1b52-6d90-4e7a-8b12-05a4c9d3f871'}</string>`,
        '</dict>',
        '</plist>',
        '',
    ].join('\n');
}
