const CLASS_DOCS: Readonly<Record<string, string>> = {
    Account: 'A registered account in the server user database. It carries the login name, the stored password data and the account data that survives a reconnect.',
    ACL: 'An access control list from `acl.xml`: a named set of rights that groups are attached to, which is what decides whether a resource may call a protected function.',
    ACLGroup: 'A group in `acl.xml`. It holds objects — players, resources — and the access control lists applied to them.',
    Ban: 'An entry in the ban list: a serial, an IP or a username barred from the server, with the reason, the admin who added it and when it expires.',
    Blip: 'A dot on the radar and on the map. It sits at a fixed position or follows the element it was attached to, and its icon, colour and visible distance are yours to set.',
    Browser: 'A CEF web browser rendered into a texture. It loads remote URLs or pages served by the resource itself, and JavaScript on the page can talk back to Lua.',
    Camera: 'The camera of the local player. It reads and moves the view point, follows a target element, applies the matrix directly and drives fades and interiors.',
    ColShape: 'An invisible volume — sphere, cube, circle, polygon, tube or rectangle — that fires a hit event when an element enters it and a leave event when it goes out.',
    Connection: 'A database connection opened with `dbConnect`. Queries are issued through it and it stays open until the resource stops or it is destroyed.',
    DxFont: 'A font loaded from a file and kept in memory for the dx drawing functions, so text can be drawn in a typeface the game does not ship.',
    DxRenderTarget: 'An off-screen surface you draw into and then render like any other texture. It is how a scene is composed once and reused across frames.',
    DxScreenSource: 'A texture that captures what is currently on screen, so the frame can be fed back into a shader or drawn again somewhere else.',
    DxShader: 'A compiled HLSL effect. It replaces a world texture or draws geometry directly, and its parameters are set from Lua while it runs.',
    DxTexture: 'An image loaded into video memory for the dx drawing functions. It is drawn, tiled or handed to a shader as a parameter.',
    Effect: 'A game particle effect — smoke, fire, sparks, water — placed in the world at a position or attached to another element.',
    Element: 'The base of everything that exists in the world. Position, rotation, dimension, interior, parenting, attachment and element data live here, and every other element class inherits them.',
    Engine: 'The entry point to the model engine. Its static methods load and replace models, textures and collisions, and read what the game already has loaded.',
    EngineCOL: 'A collision file loaded from the resource, ready to replace the collision of a game model.',
    EngineDFF: 'A model file loaded from the resource, ready to replace the geometry of a game model.',
    EngineTXD: 'A texture dictionary loaded from the resource. Import it into a model id to replace the textures that model draws with.',
    File: 'A file inside a resource, opened for reading and writing. The handle keeps its own cursor, so reads and writes continue where the last one stopped.',
    GuiBrowser: 'A widget that embeds a web browser in the GUI. The browser behind it is reached through `getBrowser` and driven like any other browser.',
    GuiButton: 'A clickable button. It fires a click event and can be a normal push button or a plain flat one.',
    GuiCheckbox: 'A labelled box that toggles between checked and unchecked, and reports which of the two it is on.',
    GuiCombobox: 'A drop-down list. Items are added, removed and read back, and one of them is the current selection.',
    GuiEdit: 'A single-line text field. It reads and writes its text, masks it for passwords, caps its length and tracks the caret.',
    GuiElement: 'The base of every GUI widget. Position, size, visibility, text, alpha, parenting and input focus live here, and every other GUI class inherits them.',
    GuiFont: 'A font loaded from a file for the GUI widgets, so a label or an edit box can use a typeface the game does not ship.',
    GuiGridList: 'A table of rows and columns. Columns are declared once, rows are added and filled cell by cell, and the selection is read back by row and column.',
    GuiLabel: 'A piece of static text. It sets its own font, colour and alignment and does not take input.',
    GuiMemo: 'A multi-line text area. It reads and writes its whole text, tracks the caret and can be made read-only.',
    GuiRadioButton: 'One option among several. Selecting it clears the other radio buttons that share its parent.',
    GuiStaticImage: 'An image widget. It is loaded from an image file in the resource and can be re-pointed at another file later.',
    GuiTab: 'One tab inside a tab panel. It is a container, so the widgets of that page are parented to it.',
    GuiTabPanel: 'A container of tabs. It creates the tab strip and reports which tab is currently selected.',
    GuiWindow: 'A titled frame that hosts other widgets. It can be dragged, sized and made modal, and it is the usual root of a GUI.',
    Light: 'A dynamic light in the world, either a point light or a spot light, with its own colour, radius and direction.',
    Marker: 'A visible spot a player walks into — a cylinder, a checkpoint, an arrow, a ring. It fires a hit event and its size, colour and target are yours to set.',
    Material: 'The base of everything the dx functions can draw: textures, shaders, render targets and screen sources all inherit it.',
    Object: 'A world model placed in the map. It can be moved and rotated over time, scaled, made breakable and toggled between visible states.',
    Ped: 'A character in the world that no one is playing. It has health, armour, weapons, animations, a vehicle seat and a task to run, and `Player` inherits all of it.',
    Pickup: 'A collectable that respawns on its own. Walking into it gives health, armour or a weapon, or fires an event when it is a custom one.',
    Player: 'A player connected to the server. On top of everything a ped has, it carries the name, the account, the money, the team, the camera and the connection.',
    Projectile: 'A rocket, grenade, molotov or teargas in flight. It knows its creator, its target, its type and how long is left before it detonates.',
    RadarArea: 'A coloured rectangle drawn on the radar and on the map, used to mark a region rather than a point.',
    RenderTarget: 'A drawing surface the dx functions render into instead of the screen, so what was drawn survives to the next frame.',
    Resource: 'A resource on the server: its name, its state, the files it holds, the functions it exports and the settings declared in its manifest.',
    Searchlight: 'A cone of light between two points, like the one under the police helicopter, with its own start and end radius.',
    Shader: 'A compiled shader applied to the world. It replaces the texture of a model or draws with a custom effect, and its parameters are set while it runs.',
    Sound: 'A playing sound or stream. Volume, speed, pan and playback position are read and written, and a sound created in the world is positional.',
    Team: 'A named group of players with a colour and a friendly-fire setting. Players are moved into it and read back from it.',
    Timer: 'A scheduled call. It runs a function after a delay, a fixed number of times or forever, and reports how long is left before the next run.',
    Vehicle: 'A car, bike, boat, plane or helicopter. Doors, engine, lights, colours, upgrades, damage, handling, towing and the occupants of every seat are all here.',
    Water: 'A custom water surface built from three or four corners, with its own level, so water can exist where the map has none.',
    Weapon: 'A custom weapon that exists on its own, without a ped holding it. It is aimed, fired and configured through its own properties.',
    XML: 'An XML document loaded from a file or created from scratch. It is saved back explicitly and reaches its content through the root node.',
    XmlNode: 'A node inside an XML document: its name, its value, its attributes and the child nodes below it.',
};

export function findOopClassDocumentation(name: string): string | null {
    return CLASS_DOCS[name] ?? null;
}

export function oopClassDocumentation(name: string): string {
    return CLASS_DOCS[name] ?? '';
}
