import { describe, expect, it } from 'vitest';

import { LanguageService } from '@lsp/server/language-service';
import { pathToUri } from '@lsp/workspace/document-uri';

import { createWorkspace, positionOf, removeWorkspace, uriFor } from './support/service-fixture';

const SERVER_FILE = pathToUri('/project/src/server/main.luam');

function hoverText(text: string, anchor: string, word: string): string {
    const service = new LanguageService();

    service.update(SERVER_FILE, 1, text);

    const hover = service.hover(SERVER_FILE, positionOf(text, anchor, word));
    const contents = hover?.contents;

    if (contents === undefined || typeof contents === 'string' || Array.isArray(contents)) {
        return '';
    }

    return contents.value;
}

describe('hover', () => {
    it('shows the annotated type of a local', () => {
        const text = 'local health: number = 100\nlocal copy = health\n';

        expect(hoverText(text, 'copy', 'health')).toContain('local health: number');
    });

    it('shows the inferred type of an unannotated local', () => {
        const text = 'local name = "thigas"\nlocal copy = name\n';

        expect(hoverText(text, 'copy', 'name')).toContain('local name: string');
    });

    it('shows the signature of a function', () => {
        const text = 'function greet(name: string, tag?: string): string\n    return name\nend\n\ngreet("a")\n';

        expect(hoverText(text, '\ngreet(', 'greet')).toContain('greet(name: string, tag?: string): string');
    });

    it('shows the inferred return type of an unannotated function', () => {
        const text = 'function greet()\n    return "hello"\nend\n\ngreet()\n';

        expect(hoverText(text, '\ngreet(', 'greet')).toContain('greet(): string');
    });

    it('shows the signature of a parameter', () => {
        const text = 'function greet(name: string): string\n    return name\nend\n';

        expect(hoverText(text, 'return', 'name')).toContain('parameter name: string');
    });

    it('shows the declaration of a class', () => {
        const text = 'class Player {\n    name: string\n}\n\nlocal one = new Player()\n';

        expect(hoverText(text, 'new ', 'Player')).toContain('class Player');
    });

    it('shows the parent of a class that extends another', () => {
        const text = 'class Base {\n    health: number = 1\n}\n\nclass Vip extends Base {\n}\n';

        expect(hoverText(text, 'class Vip', 'Vip')).toContain('class Vip extends Base');
    });

    it('shows a class member with its owner', () => {
        const text = 'class Player {\n    name: string\n}\n\nlocal one = new Player()\nlocal value = one.name\n';

        expect(hoverText(text, 'one.', 'name')).toContain('field name: string');
    });

    it('shows the inferred return type of an unannotated class method', () => {
        const text = 'class Text {\n    name: string\n    describe = function ()\n        return self.name\n    end\n}\nlocal text = new Text()\ntext:describe()\n';

        expect(hoverText(text, 'text:', 'describe')).toContain('describe(): string');
    });

    it('renders an optional field marker on the field name', () => {
        const text = 'class Player {\n    name?: string\n}\n\nlocal one = new Player()\nlocal value = one.name\n';

        expect(hoverText(text, 'one.', 'name')).toContain('field name?: string');
    });

    it('renders an object type with its keys', () => {
        const text = 'function take(args: { name: string, tag?: string }): void\n    print(args)\nend\n';

        expect(hoverText(text, 'print(', 'args')).toContain('parameter args: { name: string, tag?: string }');
    });

    it('explains the exact accessor generated by a decorator', () => {
        const boolean = 'class Player {\n    @Getter\n    admin: boolean\n}\n';
        const alias = 'type Flag = boolean\nclass Player {\n    @Getter\n    admin: Flag\n}\n';

        expect(hoverText(boolean, '@', 'Getter')).toContain('Generates `isAdmin(): boolean`');
        expect(hoverText(alias, '@', 'Getter')).toContain('Generates `isAdmin(): Flag`');
    });

    it('shows generated methods like authored methods', () => {
        const text = 'class Player {\n    @Getter\n    name: string\n}\nlocal player = new Player()\nlocal name = player:getName()\n';

        expect(hoverText(text, 'player:', 'getName')).toContain('getName(): string');
    });

    it('shows an mta api signature with its environment', () => {
        const text = 'kickPlayer(source)\n';
        const hover = hoverText(text, '', 'kickPlayer');

        expect(hover).toContain('function kickPlayer');
        expect(hover).toContain('mta api (server)');
    });

    it('shows a shared mta api with its environment', () => {
        const hover = hoverText('outputChatBox("hello")\n', '', 'outputChatBox');

        expect(hover).toContain('function outputChatBox');
        expect(hover).toContain('mta api (shared)');
    });

    it('shows a class declared in another file with its constructor and origin', () => {
        const service = new LanguageService();
        const shared = pathToUri('/project/src/shared/core.luam');
        const text = "local core: Core = new Core('client')\n";
        const source = ["class Core {", "    side: string = ''", '', '    constructor = function (side: string)', '        self.side = side', '    end', '}', ''];

        service.update(shared, 1, source.join('\n'));
        service.update(SERVER_FILE, 1, text);

        const annotation = service.hover(SERVER_FILE, positionOf(text, ': Core', 'Core'));
        const instantiation = service.hover(SERVER_FILE, positionOf(text, 'new ', 'Core'));
        const contents = annotation?.contents;
        const value = contents !== undefined && typeof contents !== 'string' && !Array.isArray(contents) ? contents.value : '';

        expect(value).toContain('class Core {\n    side: string\n\n    constructor(side: string)\n}');
        expect(value).toContain('declared in /project/src/shared/core.luam (shared)');
        expect(instantiation).not.toBeNull();
    });

    it('lists the members of a class and of an interface', () => {
        const source = [
            'interface Named {',
            '    name: string',
            '    describe(): string',
            '}',
            '',
            'class Account implements Named {',
            "    name: string = ''",
            '',
            '    describe = function (): string',
            '        return self.name',
            '    end',
            '}',
            '',
            'local account: Account = nil',
            'local named: Named = nil',
            '',
        ].join('\n');

        expect(hoverText(source, 'local account: ', 'Account')).toContain('class Account implements Named {\n    name: string\n\n    describe(): string\n}');
        expect(hoverText(source, 'local named: ', 'Named')).toContain('interface Named {\n    name: string\n\n    describe(): string\n}');
    });

    it('shows an empty body for a class without members', () => {
        const source = 'class Marker {\n}\n\nlocal marker: Marker = nil\n';

        expect(hoverText(source, 'local marker: ', 'Marker')).toContain('class Marker {}');
    });

    it('names the origin relative to the workspace root', () => {
        const root = createWorkspace({
            'src/shared/core.luam': 'class Core {\n}\n',
            'src/server/main.luam': 'local core: Core = new Core()\n',
        });
        const service = new LanguageService();
        const text = 'local core: Core = new Core()\n';

        try {
            service.loadWorkspace([root]);

            const hover = service.hover(uriFor(root, 'src/server/main.luam'), positionOf(text, ': Core', 'Core'));
            const contents = hover?.contents;
            const value = contents !== undefined && typeof contents !== 'string' && !Array.isArray(contents) ? contents.value : '';

            expect(value).toContain('declared in src/shared/core.luam (shared)');
            expect(value).not.toContain(root);
        } finally {
            removeWorkspace(root);
        }
    });

    it('shows the interfaces a class implements', () => {
        const text = 'interface Named {\n    name: string\n}\n\nclass Player implements Named {\n    name: string = \'\'\n}\n\nlocal player: Player = nil\n';

        expect(hoverText(text, 'local player', 'Player')).toContain('class Player implements Named');
    });

    it('does not show a class from an environment the file cannot reference', () => {
        const service = new LanguageService();
        const client = pathToUri('/project/src/client/hud.luam');
        const text = 'local hud: Hud = new Hud()\n';

        service.update(client, 1, 'class Hud {\n    visible: boolean = true\n}\n');
        service.update(SERVER_FILE, 1, text);

        expect(service.hover(SERVER_FILE, positionOf(text, ': Hud', 'Hud'))).toBeNull();
    });

    it('returns nothing for a position without a symbol', () => {
        const service = new LanguageService();

        service.update(SERVER_FILE, 1, 'local value = 1\n');

        expect(service.hover(SERVER_FILE, { line: 5, character: 0 })).toBeNull();
    });
});

describe('project environment hover', () => {
    function environmentHover(text: string, anchor: string, word: string): string {
        const root = createWorkspace({ '.env': 'SERVER_NAME="Luam"\nMAX_PLAYERS=32\nDEBUG=false\n' });
        const service = new LanguageService();

        service.loadWorkspace([root]);
        service.update(SERVER_FILE, 1, text);

        const contents = service.hover(SERVER_FILE, positionOf(text, anchor, word))?.contents;

        removeWorkspace(root);

        if (contents === undefined || typeof contents === 'string' || Array.isArray(contents)) {
            return '';
        }

        return contents.value;
    }

    it('shows the declared keys with their configured values instead of repeating the name', () => {
        const value = environmentHover('local name = env.SERVER_NAME\n', 'local name', 'env');

        expect(value).toContain('env: {');
        expect(value).toContain('    DEBUG: boolean = false');
        expect(value).toContain('    MAX_PLAYERS: number = 32');
        expect(value).toContain("    SERVER_NAME: string = 'Luam'");
        expect(value).not.toContain('env: env');
    });

    it('quotes a value that would break out of its literal', () => {
        const root = createWorkspace({ '.env': 'MOTD="it\'s here"\n' });
        const service = new LanguageService();
        const text = 'local motd = env.MOTD\n';

        service.loadWorkspace([root]);
        service.update(SERVER_FILE, 1, text);

        const contents = service.hover(SERVER_FILE, positionOf(text, 'local motd', 'env'))?.contents;

        removeWorkspace(root);

        expect(contents === undefined || typeof contents === 'string' || Array.isArray(contents) ? '' : contents.value).toContain(
            "MOTD: string = 'it\\'s here'",
        );
    });

    it('names the file the keys come from and the environment that may read them', () => {
        expect(environmentHover('local name = env.SERVER_NAME\n', 'local name', 'env')).toContain('declared in ".env" (server)');
    });
});
