import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { MODES, type Mode } from '@theme/palette';
import { contrastTable, DOCS_LOCALES, elementTable, sampleBlock } from '@theme/targets/docs';
import { buildNeovimTheme } from '@theme/targets/neovim';
import { buildTmTheme } from '@theme/targets/tmtheme';
import { buildVsCodeTheme } from '@theme/targets/vscode';
import { buildZedTheme } from '@theme/targets/zed';

export interface GeneratedFile {
    path: string;
    contents: string;
}

const BANNER = 'Generated by @luam/theme from the role table. Do not edit by hand; run pnpm --filter @luam/theme themes.';

const FIXTURE = join('packages', 'vscode', 'tests', 'fixtures', 'theme-sample.luam');

function asJson(value: unknown): string {
    return `${JSON.stringify(value, null, 4)}\n`;
}

function vsCodeFile(mode: Mode): GeneratedFile {
    return { path: join('packages', 'vscode', 'themes', `luam-${mode}.json`), contents: asJson({ generator: BANNER, ...buildVsCodeTheme(mode) }) };
}

function docsFiles(root: string): GeneratedFile[] {
    const fixture = readFileSync(join(root, FIXTURE), 'utf8');

    return [
        { path: join('docs', 'generated', 'theme-sample.md'), contents: sampleBlock(fixture) },
        ...DOCS_LOCALES.flatMap((locale) => [
            { path: join('docs', 'generated', `theme-elements.${locale}.md`), contents: elementTable(locale) },
            { path: join('docs', 'generated', `theme-contrast.${locale}.md`), contents: contrastTable(locale) },
        ]),
    ];
}

export function generatedFiles(root: string): GeneratedFile[] {
    return [
        ...MODES.map(vsCodeFile),
        { path: join('packages', 'theme', 'dist-themes', 'luam-zed.json'), contents: asJson({ generator: BANNER, ...buildZedTheme() }) },
        { path: join('packages', 'theme', 'dist-themes', 'luam.lua'), contents: buildNeovimTheme() },
        ...MODES.map((mode) => ({ path: join('packages', 'theme', 'dist-themes', `luam-${mode}.tmTheme`), contents: buildTmTheme(mode) })),
        ...docsFiles(root),
    ];
}

export function writeTargets(root: string): string[] {
    return generatedFiles(root).map((file) => {
        const target = join(root, file.path);

        mkdirSync(dirname(target), { recursive: true });
        writeFileSync(target, file.contents, 'utf8');

        return file.path;
    });
}

export function staleTargets(root: string): string[] {
    return generatedFiles(root)
        .filter((file) => {
            try {
                return readFileSync(join(root, file.path), 'utf8') !== file.contents;
            } catch {
                return true;
            }
        })
        .map((file) => file.path);
}
