const CLASS_HOVER = [
    '```luam',
    'class Name { ... }',
    '```',
    '',
    '`class` declares a runtime class: fields, a constructor, and methods. It compiles to a call into the `class` runtime helper, included only when the resource declares a class; interfaces and annotations contribute nothing.',
    '',
    '**Header**',
    '',
    '- `class Name extends Parent` inherits fields and methods from another class.',
    '- `class Name implements Shape, Other` asks the checker to verify each interface contract.',
    '',
    '**Members**',
    '',
    '- A field is `name: Type` with an optional default: `balance: number = 0`.',
    '- The constructor and methods are written `name = function (...) ... end`; the typed `self` is injected automatically.',
    '',
    '**Rules**',
    '',
    '- A class is a type everywhere in its file and a value from the line its declaration runs; instantiating it earlier in top-level code is `check-class-before-declaration`.',
    '- Two classes with one name in a file is `check-duplicate-class`; an inheritance cycle is `check-class-cycle`.',
    '- Static members, declared metamethods, and generic classes are not supported.',
].join('\n');

const CONSTRUCTOR_HOVER = [
    '```luam',
    'constructor = function (...) ... end',
    '```',
    '',
    '`constructor` is the class initializer. `new Name(...)` runs it with the arguments checked against its parameters.',
    '',
    '**Binding**',
    '',
    '- It receives the typed `self` implicitly; writing `self` as a parameter is `check-explicit-self-parameter`.',
    '- In a class with `extends`, `super(...)` inside it calls the parent constructor.',
    '',
    '**Rules**',
    '',
    '- It is a class member, never a field: `constructor: Type` is `check-invalid-constructor`.',
    '- A class without one still instantiates; fields keep their defaults and a field with neither a default nor an assignment starts as `nil`.',
].join('\n');

const NEW_HOVER = [
    '```luam',
    'new Name(...)',
    '```',
    '',
    '`new` instantiates a class, calling its `constructor` with the given arguments and producing a value typed as the class.',
    '',
    '**Checking**',
    '',
    '- The argument list is checked against the constructor parameters.',
    '- Fields are read with `.` and methods are called with `:` on the instance — the Lua rule, unchanged.',
    '',
    '**Rules**',
    '',
    '- `new` on a name that is not a class is `check-unknown-class`.',
    '- At the top level, instantiating a class declared further down is `check-class-before-declaration`; inside a function body it is fine.',
    '- Native runtime classes (`Threads`, `Async`) use the same `new`; their helper is injected only when the class is named.',
].join('\n');

const EXTENDS_HOVER = [
    '```luam',
    'class Child extends Parent { ... }',
    "interface Entity extends Named, Identified { ... }",
    '```',
    '',
    '`extends` declares inheritance for a class or an interface.',
    '',
    '**On a class**',
    '',
    '- A class extends one parent class and inherits its fields and methods.',
    '- `super(...)` in the constructor calls the parent constructor; in a method, the parent method with the same name.',
    '- The parent may be written further down in the file: a class is a type everywhere in its file.',
    '',
    '**On an interface**',
    '',
    '- An interface extends one or more interfaces and inherits every field and method; implementing classes must satisfy the complete contract.',
    '- Compatible inherited declarations are merged; incompatible ones are `check-conflicting-interface-member`.',
    '',
    '**Rules**',
    '',
    '- An inheritance cycle is `check-class-cycle`; extending a native runtime class is `check-native-class-inheritance`.',
    '- Naming an interface that does not exist is `check-unknown-interface`.',
].join('\n');

const IMPLEMENTS_HOVER = [
    '```luam',
    'class Name implements Shape, Other { ... }',
    '```',
    '',
    '`implements` asks the checker to verify that the class satisfies every member of each interface. It changes nothing at runtime — an interface never reaches the generated Lua.',
    '',
    '**Checking**',
    '',
    '- Every required interface member must exist in the class with an assignable type.',
    '- An optional member (`name?: Type`) may be omitted; when the class does declare it, the type still has to match.',
    '- The contract includes everything the interface inherits through `extends`.',
    '',
    '**Rules**',
    '',
    '- A missing or mismatched member is `check-unimplemented-interface`, and the message names it.',
    '- Naming an interface that does not exist is `check-unknown-interface`.',
].join('\n');

export const CLASS_KEYWORD_TEXT: ReadonlyMap<string, string> = new Map([
    ['class', CLASS_HOVER],
    ['constructor', CONSTRUCTOR_HOVER],
    ['new', NEW_HOVER],
    ['extends', EXTENDS_HOVER],
    ['implements', IMPLEMENTS_HOVER],
]);
