import type { Hover, Range } from 'vscode-languageserver';

import type { DocumentAnalysis } from '@lsp/analysis/document-analysis';
import { containerShape, markdown } from '@lsp/features/declaration-shape';
import { toWordRange } from '@lsp/support/lsp-position';
import { positionAt, wordAt, wordStart } from '@lsp/support/source-text';

const SUPER_HOVER = [
    '```luam',
    'super(...): ParentReturnType',
    '```',
    '',
    '`super(...)` calls the parent-class implementation for the current class member while preserving the current `self` instance.',
    '',
    '**Resolution**',
    '',
    '- In a constructor, it invokes the parent-class constructor.',
    '- In an overridden method, it invokes the parent implementation of the method with the same name.',
    '- Dispatch starts from the declared parent class instead of calling the overriding implementation again.',
    '',
    '**Type checking**',
    '',
    '- Arguments are checked against the selected parent constructor or method parameters.',
    '- The expression type is the return type of the selected parent implementation, so its result can be returned or assigned.',
    '',
    '**Restrictions**',
    '',
    '- It is only valid inside a class member whose class declares a parent with `extends`.',
    '- Call it directly as `super(...)`; the legacy form `self:super(...)` is invalid.',
    '- A missing parent method produces `check-unknown-super-method`; use outside a valid class context produces `check-invalid-super`.',
].join('\n');

const SELF_SUMMARY = '`self` is the receiver of the current class member. It is bound implicitly, so it is never written in the parameter list and never declared as a local.';

const SELF_RULES = [
    '**Binding**',
    '',
    '- Every instance member of a class receives it, including the constructor and the members generated by a decorator.',
    '- A `function Name:method()` declaration receives it too; the dot form `function Name.method()` does not.',
    '',
    '**Restrictions**',
    '',
    '- Writing it as a parameter produces `check-explicit-self-parameter`; the compiler already injects it.',
    '- Outside a class member it reads a global that is `nil`, which is `check-invalid-self`.',
].join('\n');

const UNBOUND_SELF = ['```luam', 'self', '```', '', SELF_SUMMARY, '', 'It is not bound here, so this reads a global that is `nil`: `check-invalid-self`.', '', SELF_RULES].join('\n');

function wordRange(analysis: DocumentAnalysis, offset: number, word: string): Range {
    return toWordRange(positionAt(analysis.starts, wordStart(analysis.text, offset)), word);
}

function selfHover(analysis: DocumentAnalysis, offset: number): Hover {
    const declaration = analysis.index.declarationFor(offset);
    const owner = declaration?.name === 'self' && declaration.type?.kind === 'named' ? declaration.type.name : null;

    if (owner === null) {
        return { contents: { kind: 'markdown', value: UNBOUND_SELF }, range: wordRange(analysis, offset, 'self') };
    }

    const shape = containerShape(analysis, owner);
    const instance = shape === null ? [] : ['', '**Instance**', '', markdown(shape)];
    const value = [markdown(`self: ${owner}`), '', SELF_SUMMARY, ...instance, '', SELF_RULES].join('\n');

    return { contents: { kind: 'markdown', value }, range: wordRange(analysis, offset, 'self') };
}

function isReceiverMember(analysis: DocumentAnalysis, offset: number): boolean {
    const before = analysis.text[wordStart(analysis.text, offset) - 1];

    return before === '.' || before === ':';
}

export function contextualHover(analysis: DocumentAnalysis, offset: number): Hover | null {
    const word = wordAt(analysis.text, offset);

    if (word === 'self') {
        return isReceiverMember(analysis, offset) ? null : selfHover(analysis, offset);
    }

    return word === 'super' ? { contents: { kind: 'markdown', value: SUPER_HOVER } } : null;
}
