const INTERFACE_HOVER = [
    '```luam',
    'interface Name { ... }',
    '```',
    '',
    '`interface` declares a compile-only contract of fields and methods. It is verified by the checker and never reaches the generated Lua.',
    '',
    '**Usage**',
    '',
    '- A class states that it satisfies one with `implements`.',
    '- An interface is also usable as a type: `local target: Describable = new Round()`.',
    '- `interface Child extends A, B` inherits every member of its parents.',
    '',
    '**Rules**',
    '',
    '- A missing member in an implementing class is `check-unimplemented-interface`.',
    '- An optional member is written `name?: Type` and may be omitted by implementers.',
    '- Declaring the same interface twice is `check-duplicate-interface`; incompatible inherited members are `check-conflicting-interface-member`.',
].join('\n');

const ENUM_HOVER = [
    '```luam',
    'enum Name { FIRST, SECOND }',
    '```',
    '',
    '`enum` declares a fixed set of named numbers. Members are zero-based (`FIRST` is `0`) and typed `number`, so a member is usable anywhere a number is expected — including as an MTA argument.',
    '',
    '**Emission**',
    '',
    "- It reaches the generated Lua as a call into the `enum` runtime helper: `Name = enum { 'FIRST', 'SECOND' }`.",
    '- An enum no file in the resource reads is erased silently; a surviving enum is a global, so `loadOrder` matters when another file reads it while loading.',
    '',
    '**Local enums**',
    '',
    '- `local enum` scopes it to the declaring file, like a `local function`: no other file sees it, and `loadOrder` never matters for it.',
    '- An unread local enum is `check-unused-local` under `noUnusedLocals`; an unread global enum is erased silently instead.',
    '',
    '**Rules**',
    '',
    '- An unknown member is `check-unknown-enum-member`, and the message lists the members that exist.',
    '- Declaring the same enum name twice in one file is `check-duplicate-enum`.',
].join('\n');

const TYPE_HOVER = [
    '```luam',
    'type Name = ...',
    '```',
    '',
    '`type` gives a name to a type. An alias is erased entirely and contributes nothing to the generated Lua.',
    '',
    '**Usage**',
    '',
    '- `type PlayerId = number`, `type SpawnArgs = { name: string, team?: string }`.',
    '- Aliases may be generic: `type Nullable<T> = T | nil`.',
    '- Unions, intersections, arrays, maps, and literal types all work on the right-hand side.',
    '',
    '**Still callable**',
    '',
    "- Lua's `type(value)` function is untouched; in a condition, `type(value) == '...'` narrows the value to that type.",
].join('\n');

const DECLARE_HOVER = [
    '```luam',
    'declare Name: Type',
    "declare event 'name'(...)",
    '```',
    '',
    '`declare` binds a global or a custom event to a type without emitting anything.',
    '',
    '**Globals**',
    '',
    '- `declare NAME: Type` is valid only inside a `.d.luam` declaration file; elsewhere it is `check-declare-outside-declaration-file`.',
    '- Where a declaration and real source name the same global, the declaration wins and the source is checked against it.',
    '',
    '**Events**',
    '',
    "- `declare event 'name'(parameters)` gives a custom MTA event a typed contract; every handler and trigger of that name is checked against it.",
    '- The event form is valid in ordinary source too, because it emits nothing either way.',
].join('\n');

const EXPORT_HOVER = [
    '```luam',
    'export function name(...) ... end',
    '```',
    '',
    "`export` marks a top-level function as callable by other MTA resources. The keyword is erased from the generated Lua; what it produces is an `<export />` entry in `meta.xml`, typed after the file's environment.",
    '',
    '**HTTP**',
    '',
    '- `export http function ...` emits `http="true"`, letting MTA\'s HTTP server call the function; without the modifier the compiler emits `http="false"`.',
    '',
    '**Rules**',
    '',
    '- Top-level functions only: `check-export-not-top-level`; a plain global name, not a table member: `check-export-member`.',
    '- A `.d.luam` file emits no code, so it cannot export: `check-export-in-declaration-file`.',
    '- Two files may not export the same name: `project-duplicate-export`; `export` on a `local function` is `parse-export-local`.',
].join('\n');

const CONTINUE_HOVER = [
    '```luam',
    'continue',
    '```',
    '',
    '`continue` skips to the next iteration of the innermost `for`, `while` or `repeat`. Lua 5.1 has neither `continue` nor `goto`, so the compiler lowers the loop body into a `repeat ... until true` block, which costs nothing at runtime; a loop without `continue` is emitted exactly as before.',
    '',
    '**Rules**',
    '',
    '- It only appears inside a loop, and a function body inside a loop is not the same level: `check-invalid-continue`.',
    '- It must be the last statement of its block — the Lua 5.1 rule for `break`.',
    '- Inside a `repeat`, it cannot jump over a local the `until` condition reads; declare the local above the loop, or use `while`.',
].join('\n');

export const DECLARATION_KEYWORD_TEXT: ReadonlyMap<string, string> = new Map([
    ['interface', INTERFACE_HOVER],
    ['enum', ENUM_HOVER],
    ['type', TYPE_HOVER],
    ['declare', DECLARE_HOVER],
    ['export', EXPORT_HOVER],
    ['continue', CONTINUE_HOVER],
]);
