import { Reader, type ExtractProblem } from './config-reader';

export const GENERATED_MARKER = '# Generated by "luam config" from';

const MAX_SOURCE_BYTES = 262144;

const MAX_DEPTH = 8;

const MAX_ENTRIES = 512;

export interface ExtractedDeclaration {
    name: string;
    type: string;
}

export interface ExtractResult {
    declarations: ExtractedDeclaration[];
    problems: ExtractProblem[];
}

type Value = { kind: 'literal'; type: string } | { kind: 'array'; element: string } | { kind: 'record'; fields: [string, string][] } | { kind: 'table' };

function renderRecord(fields: readonly [string, string][]): string {
    return `{ ${fields.map(([name, type]) => `${name}: ${type}`).join(', ')} }`;
}

function render(value: Value): string {
    if (value.kind === 'literal') {
        return value.type === 'nil' ? 'any' : value.type;
    }

    if (value.kind === 'array') {
        return `${value.element}[]`;
    }

    return value.kind === 'record' && value.fields.length > 0 ? renderRecord(value.fields) : 'table';
}

function unify(types: readonly string[]): string {
    const unique = [...new Set(types)];

    return unique.length === 1 ? (unique[0] ?? 'any') : 'any';
}

function readTable(reader: Reader, depth: number): Value | null {
    if (depth > MAX_DEPTH) {
        return reader.fail(`A table nested deeper than ${MAX_DEPTH} levels is not extracted.`);
    }

    const fields: [string, string][] = [];
    const elements: string[] = [];

    for (let count = 0; ; count += 1) {
        if (reader.take('}')) {
            break;
        }

        if (count > MAX_ENTRIES) {
            return reader.fail(`A table with more than ${MAX_ENTRIES} entries is not extracted.`);
        }

        const key = reader.key();
        const value = readValue(reader, depth + 1);

        if (value === null) {
            return null;
        }

        if (key === null) {
            elements.push(render(value));
        } else {
            fields.push([key, render(value)]);
        }

        if (!reader.take(',') && !reader.take(';') && reader.peek() !== '}') {
            return reader.fail('Expected "," or "}" in a table.');
        }
    }

    if (fields.length > 0 && elements.length > 0) {
        return { kind: 'table' };
    }

    return elements.length > 0 ? { kind: 'array', element: unify(elements) } : { kind: 'record', fields };
}

function readValue(reader: Reader, depth: number): Value | null {
    if (reader.take('{')) {
        return readTable(reader, depth);
    }

    const literal = reader.literal();

    if (literal === null) {
        return reader.fail('Only literals and table constructors are extracted. Declare this value by hand.');
    }

    if (reader.peek() === '.' || reader.peek() === '(' || reader.peek() === '+') {
        return reader.fail('An expression is not extracted. Declare this value by hand.');
    }

    return { kind: 'literal', type: literal };
}

export function extractConfigDeclarations(source: string): ExtractResult {
    if (source.length > MAX_SOURCE_BYTES) {
        return { declarations: [], problems: [{ line: 1, column: 1, message: `A file larger than ${MAX_SOURCE_BYTES} bytes is not extracted.` }] };
    }

    const reader = new Reader(source);
    const declarations = new Map<string, string>();

    while (!reader.done()) {
        reader.take('local');

        const name = reader.word();

        if (name === null || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(name) || !reader.take('=')) {
            reader.fail('Only a top-level assignment of a literal or a table is extracted.');

            break;
        }

        const value = readValue(reader, 1);

        if (value === null) {
            break;
        }

        declarations.set(name, render(value));
        reader.take(';');
    }

    return { declarations: [...declarations].map(([name, type]) => ({ name, type })), problems: reader.problems };
}

export function renderConfigDeclarations(source: string, declarations: readonly ExtractedDeclaration[]): string {
    const lines = declarations.map((declaration) => `declare ${declaration.name}: ${declaration.type}`);

    return `${GENERATED_MARKER} "${source}". Do not edit.\n\n${lines.join('\n')}\n`;
}

export function isGeneratedDeclaration(text: string): boolean {
    return text.startsWith(GENERATED_MARKER);
}
