import { afterEach, describe, expect, it } from 'vitest';

import { runConfigCommand } from '@cli/commands/config-command';
import { EXIT_DIAGNOSTICS, EXIT_OK } from '@cli/cli/exit-codes';

import { createMemoryLogger, type MemoryLogger } from './support/memory-logger';
import { createProjectFixture, defaultProjectFiles, type ProjectFixture } from './support/project-fixture';
import { createReporter } from '@cli/reporting/reporter';
import { PLAIN_CAPABILITY } from '@cli/reporting/output-capability';

const fixtures: ProjectFixture[] = [];

const CONFIG = `-- Resource configuration
NAME = 'core'
MAX_PLAYERS = 32
DATABASE = { host = 'localhost', port = 3306 }
SPAWNS = { 1, 2, 3 }
`;

interface Harness {
    fixture: ProjectFixture;
    logger: MemoryLogger;
    run: (options?: Parameters<typeof runConfigCommand>[2]) => number;
}

function harness(files: Readonly<Record<string, string>>): Harness {
    const fixture = createProjectFixture({ ...defaultProjectFiles(), ...files });
    const logger = createMemoryLogger();

    fixtures.push(fixture);

    return {
        fixture,
        logger,
        run: (options = {}): number => runConfigCommand(fixture.root, createReporter(logger, PLAIN_CAPABILITY), options),
    };
}

afterEach(() => {
    for (const fixture of fixtures.splice(0)) {
        fixture.dispose();
    }
});

describe('config command', () => {
    it('prints the declarations without writing anything', () => {
        const { run, logger, fixture } = harness({ 'config.lua': CONFIG });

        expect(run()).toBe(EXIT_OK);
        expect(logger.text()).toContain('declare NAME: string');
        expect(logger.text()).toContain('declare DATABASE: { host: string, port: number }');
        expect(fixture.exists('config.d.luam')).toBe(false);
    });

    it('writes the declarations when asked', () => {
        const { run, fixture } = harness({ 'config.lua': CONFIG });

        expect(run({ write: true })).toBe(EXIT_OK);
        expect(fixture.exists('config.d.luam')).toBe(true);
        expect(fixture.read('config.d.luam')).toContain('declare SPAWNS: number[]');
    });

    it('marks the file it generated', () => {
        const { run, fixture } = harness({ 'config.lua': CONFIG });

        run({ write: true });

        expect(fixture.read('config.d.luam').startsWith('# Generated by "luam config" from')).toBe(true);
    });

    it('writes the same bytes twice', () => {
        const { run, fixture } = harness({ 'config.lua': CONFIG });

        run({ write: true });

        const first = fixture.read('config.d.luam');

        run({ write: true });

        expect(fixture.read('config.d.luam')).toBe(first);
    });

    it('refuses to overwrite a hand-written declaration', () => {
        const { run, logger, fixture } = harness({ 'config.lua': CONFIG, 'config.d.luam': 'declare NAME: string\n' });

        expect(run({ write: true })).toBe(EXIT_DIAGNOSTICS);
        expect(logger.text()).toContain('was not generated by this command');
        expect(fixture.read('config.d.luam')).toBe('declare NAME: string\n');
    });

    it('reports a missing source', () => {
        const { run, logger } = harness({});

        expect(run()).toBe(EXIT_DIAGNOSTICS);
        expect(logger.text()).toContain('found no file at "config.lua"');
    });

    it('refuses a source outside the project', () => {
        const { run, logger } = harness({ 'config.lua': CONFIG });

        expect(run({ source: '../outside.lua' })).toBe(EXIT_DIAGNOSTICS);
        expect(logger.text()).toContain('points outside it');
    });

    it('refuses an output outside the project', () => {
        const { run, logger } = harness({ 'config.lua': CONFIG });

        expect(run({ write: true, out: '../escape.d.luam' })).toBe(EXIT_DIAGNOSTICS);
        expect(logger.text()).toContain('points outside it');
    });

    it('warns about content it cannot extract and keeps the rest', () => {
        const { run, logger, fixture } = harness({ 'config.lua': "NAME = 'core'\nHANDLER = getResourceName()\n" });

        expect(run({ write: true })).toBe(EXIT_OK);
        expect(logger.text()).toContain('Declare this value by hand');
        expect(fixture.read('config.d.luam')).toContain('declare NAME: string');
    });

    it('reports a file with nothing to declare', () => {
        const { run, logger } = harness({ 'config.lua': 'function handle()\nend\n' });

        expect(run()).toBe(EXIT_DIAGNOSTICS);
        expect(logger.text()).toContain('found nothing to declare');
    });

    it('reads a source the caller names', () => {
        const { run, fixture } = harness({ 'settings/config.lua': CONFIG });

        expect(run({ write: true, source: 'settings/config.lua', out: 'settings/config.d.luam' })).toBe(EXIT_OK);
        expect(fixture.exists('settings/config.d.luam')).toBe(true);
    });
});
